### ISSUE TITLE
could not parse properties ended with "," | 无法解析谱面文件中逗号结尾的action

### ISSUE THREAD

**Issue by sblzdddd** [CkbltIsCoding/Adofai#1]
这个貌似是python json库自己的问题，大概就是在“actions”列表中只要有
`{..., "editorOnly": false, }`
或者
`{..., "eventTag": “”, }`
这种结尾有一个多出来的","
就会报错：
`json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line {...} column {...} (char 111962)`
目前唯一的解决办法是找查替换.adofai文件里面“, }”的样式

**Comment by CkbltIsCoding** [comment]
修复了
在`process_data`方法中的第一段改成这样
```python
        with open(
            self.path, "r", encoding="utf-8-sig"
        ) as f:
            string = f.read()
            string = re.sub(",(?=\\s*?[}\\]])", "", string)  # 删除尾随逗号
            beatmap = json.loads(string, strict=False)
```

**Comment by CkbltIsCoding** [comment]
已经推送到github上了
