### ISSUE TITLE
[Question]打击音添加时间超级长

### ISSUE THREAD

**Issue by leo-2345** [CkbltIsCoding/Adofai#4]
在一些铺面中，不仅时间长，而且tile也多，导致打击音添加时间很长
在IDPLMA(unnerfed)中，经测试，大约需50min来添加打击音
建议优化add_sound函数,
或者换个效率更高的库

**Comment by CkbltIsCoding** [comment]
```python
    for index in range(len(ms_list)):
        beats = beats.overlay(beat, ms_list[index])  # 这里
        if index % 100 == 0:
            if not callback((index + 1) / len(ms_list)):
                return False
```
似乎是pydub的overlay函数执行时间较长，下周末会考虑换个函数或者换个库

**Comment by leo-2345** [comment]
经过此次优化后，在一些短的铺面中，确实得到了优化，但是在上次测试的IDPLMA(unnerfed) 中，却得到了负优化
测试结果: 
1)  2.04%  ---- 1:18
2)  2.04% ---- 1:14
3)  2.04% ---- 1:17

取平均值,结果约为 62.3638344227(分钟)
希望能针对tile多的铺面进行优化
